### ISSUE TITLE
build Clean fails on old Windows with long path error

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#265]
When I run `build Clean` on Windows 8.1, I get an error complaining about too long path (Win 8.1 has restriction on some APIs for path length around 260, which tends to break things with node). I guess Win 10 does not have this and I should just update....

That said, I wonder if the following `Clean` target [in the build script](https://github.com/fsprojects/Fable/blob/master/build.fsx#L148) isn't a bit wrong:

    !! "build/" ++ "src/**/bin/" ++ "src/**/obj/"
    |> CleanDirs

This cleans any `bin` folders inside `src`, but there are `bin` folders not just for the regular F# projects, but also inside some of the installed `node_modules` folders - and I suppose this is also where I'm getting the error.

Should this be changed to only clean actual F# `bin` and `obj` folders?

**Comment by fdcastel** [comment]
> but there are `bin` folders not just for the regular F# projects, but also inside some of the installed `node_modules` folders 

Daaaamn! Yes! You nailed it!

That's why whenever I make a `build` (full build) the `build fablecore` task stops working.

The full build breaks something in `Fable.Core/npm` and I always have to reinstall npm modules for `build fablecore` work again.

**Comment by alfonsogarciacaro** [comment]
I'm trying to fix this. Unfortunately, typescript refuses to build `fable-core.ts` after merging the refactors :( Here're the errors:

```
fable-core.ts(860,7): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
fable-core.ts(1263,9): error TS7027: Unreachable code detected.
fable-core.ts(1281,5): error TS7027: Unreachable code detected.
fable-core.ts(1888,7): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
```

**Comment by fdcastel** [comment]
Looking at it right now.

**Comment by fdcastel** [comment]
Hm. I can't reproduce this error in my machine. The build from current master (d5787207571ba407ec9d435cd95641fbbc5122cb) is going fine.

Wild guess: This errors arent' from TypeScript 2.0 beta?

**Comment by alfonsogarciacaro** [comment]
Ok, this was a tricky one. I was calling a script in package.json which should be called `tsc` locally (v1.8.0), but precisely because the build script was removing the `bin` folders, npm was defaulting to my global installation which was indeed v2.0.0 😖 

I tried to fix the build script. I wanted to exclude the `node_modules` folder when deleting `src/**/bin` but I didn't manage to do it easily, so I just took the easy path and now I'm removing only `src/**/obj` which should be enough as projects usually output assemblies to directories other than  `bin`.

In any case, it seems to be working now, also in AppVeyor. I'll try myself on Windows too later, but if it's working for you please feel free to close the issue :+1:

**Comment by fdcastel** [comment]
Looks good in Windows 8.1 with same setup described in #266 


```
Starting Target: Clean
Deleting contents of C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\build\fable\bin
Deleting contents of C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\src\fable\Fable.Client.Node\obj
Deleting contents of C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\src\fable\Fable.Compiler\obj
Deleting contents of C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\src\fable\Fable.Core\obj
Finished Target: Clean

```

**Comment by alfonsogarciacaro** [comment]
Thanks @fdcastel, I also checked on Windows 10 and it's working so I'm closing the issue :+1:
